# Generated by Django 4.2.4 on 2023-08-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0003_alter_item_item_category'),
        ('billing_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory_data.item'),
            preserve_default=False,
        ),
    ]
