# Generated by Django 4.2.4 on 2023-08-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_data', '0002_billitems_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitems',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='supplier_discount',
        ),
    ]
