# Generated by Django 4.2.4 on 2023-08-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_data', '0003_remove_billitems_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitems',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='billing_data.bill'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='billing_data.bill'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_methods',
            field=models.CharField(choices=[('select', 'Select'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('credit', 'Credit'), ('multiple', 'multiple')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='billservises',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_services', to='billing_data.bill'),
        ),
    ]
