# Generated by Django 4.2.4 on 2023-08-31 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_data', '0004_alter_billitems_bill_alter_billpayment_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcash',
            name='bill_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_cash', to='billing_data.billpayment'),
        ),
        migrations.AlterField(
            model_name='paymentcheque',
            name='bill_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cheques', to='billing_data.billpayment'),
        ),
        migrations.AlterField(
            model_name='paymentcredit',
            name='bill_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_credit', to='billing_data.billpayment'),
        ),
        migrations.AlterField(
            model_name='paymentcreditcard',
            name='bill_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_credit_card', to='billing_data.billpayment'),
        ),
    ]
