# Generated by Django 4.2.4 on 2023-09-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_data', '0002_alter_item_item_category_alter_item_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='StockItemsInvoice',
            fields=[
                ('invoice_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sales_discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_data.item')),
                ('stock_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stockitemsinvoice')),
                ('stock_item_unique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_data.stockitemunique')),
            ],
        ),
    ]
