# Generated by Django 4.2.4 on 2023-08-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_data', '0002_alter_item_item_category_alter_item_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemsInvoice',
            fields=[
                ('invoice_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.PositiveSmallIntegerField()),
                ('sold_qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.item')),
                ('stock_item_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_data.stockitemsinvoice')),
            ],
        ),
    ]
