# Generated by Django 4.2.4 on 2023-08-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_item_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockitems', to='stock_data.stockitemsinvoice'),
        ),
    ]
