# Generated by Django 4.2.4 on 2023-08-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0002_alter_item_item_category_alter_item_supplier'),
        ('stock_data', '0002_alter_stockitem_stock_item_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.item'),
        ),
    ]
