# Generated by Django 4.2.4 on 2023-08-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('plyrating', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('vale_type', models.CharField(choices=[('Long Valve', 'Long Valve'), ('Short Valve', 'Short Valve'), ('Not selected', 'Select')], default='Not selected', max_length=20)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.itemcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_data.supplier')),
            ],
        ),
    ]
