# Generated by Django 4.2.4 on 2023-10-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_data', '0002_alter_item_item_category_alter_item_supplier'),
        ('dag_section_data', '0004_alter_receivedsuppliertyre_received_tyre'),
        ('customer_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuildReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.CharField(max_length=100)),
                ('tyre_no', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('send_date', models.CharField(blank=True, max_length=100, null=True)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_data.customer')),
                ('rebuild_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dag_section_data.customertakentyre')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.supplier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_data.vehical')),
            ],
        ),
    ]
