# Generated by Django 4.2.5 on 2023-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebuildreport',
            name='job_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rebuildreport',
            name='tyre_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
