# Generated by Django 4.2.5 on 2023-10-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0002_alter_rebuildreport_job_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebuildreport',
            name='received_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
