# Generated by Django 4.2.4 on 2023-10-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0003_rebuildreport_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebuildreport',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rebuildreport',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rebuildreport',
            name='taken_date',
            field=models.DateTimeField(),
        ),
    ]
